//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVERTEC.TIENDA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaSecurity
    {
        public int AuditoriaSecurityID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tabla { get; set; }
        public string Accion { get; set; }
        public string UsuarioID { get; set; }
        public string Registros { get; set; }
        public string IP { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
