//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVERTEC.TIENDA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaDB
    {
        public int AuditoriaID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tabla { get; set; }
        public string UsuarioID { get; set; }
        public string Accion { get; set; }
        public string DatoAnterior { get; set; }
        public string DatoNuevo { get; set; }
        public string Columna { get; set; }
        public string IP { get; set; }
        public string RegistroID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
